version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    
  dtu-facade-17:
    image: dtu-facade-17
    container_name: facade
    ports:
     - "8080:8080"
    
  account-service-dtu:
    image: account-service
    container_name: account-service

  payment-service-dtu:
    image: payment-service
    container_name: payment-service

  report-service-dtu:
    image: report-service
    container_name: report-service

  token-service-dtu:
    image: token-service
    container_name: token-service

 
